In [1]:
print("helo")

helo


In [1]:
v=5
print(v)

5


In [3]:
a=23
b=12
print(a+b)

35


In [22]:
a=12
b=4
c=a/b
d=a//b
print(c)
print(d)
r=a**b
print(r)
print(a&b)
print(a|b)
print(a^b)
print(a>>b)
print(a<<b)
print(~a)
a/=10
print(a)
# a=(input("enter a string: "))
# b=(input("enter a string: "))

# print(a, "+", b)
s="ram"+ "12"
print(s)

3.0
3
20736
4
12
8
0
192
-13
1.2
ram12


In [23]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
print(list(range(0,10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [28]:
for i in range(1,30):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [29]:
for i in range(1,30,4):
    print(i)

1
5
9
13
17
21
25
29


In [32]:
for i in range(0,-20,-4):
    print(i)

0
-4
-8
-12
-16


In [34]:
print ("Sum is --> ", sum(range(1,11)))


Sum is -->  55


In [35]:

n= int(input("enter the value of n: "))
for i in range(1,11):
    print(n*i)

4
8
12
16
20
24
28
32
36
40


In [37]:
n=int(input("enter the value of n: "))
print(sum(range(1,n)))

4950


prime number

In [38]:
n=int(input("enter a number:"))
f=0
for i in range(2, int(1+n/2)):
    if n%i==0:
        f=1
        break

if f==0:
    print("prime")

else:
    print("not prime")

not prime


fibonacci

In [39]:
n=10
a=0
b=1
print(a)
print(b)
for i in range(n):
    c=a+b
    print(c)
    a=b
    b=c

0
1
1
2
3
5
8
13
21
34
55
89


factorial

In [42]:
n=4
a=1
for i in range(1,n+1):
    a=a*i
    print(a)

1
2
6
24


add 2 numbers in a function

In [44]:
def add(a,b):
    c=a+b
    return c

print(add(1,2))
print(add(1,8))

3
9


In [45]:
#------------------------------------------------------------------------
# 5.4: Default Parameter
#------------------------------------------------------------------------
def Add(a, b, d = 90):
    c = a + b + d
    return c

print ("Add(10,20)   -->", Add(10,20))
print ("Add(20,50,10)-->", Add(20,50,10))


Add(10,20)   --> 120
Add(20,50,10)--> 80


In [48]:
#------------------------------------------------------------------------
# 7.2: Difference between single quote and double quote
#------------------------------------------------------------------------
var1 = 'Hello "Python"'
var2 = "Hello 'Python'"
var3= 'Hello'
var4= "hi"
print ("var1 -->", var1)
print ("var2 -->",var2)
print ("var3 -->",var3)
print ("var4 -->",var4)


var1 --> Hello "Python"
var2 --> Hello 'Python'
var3 --> Hello
var4 --> hi


if we want to use ' in the print statement then use backslash ' for no error

In [60]:
a="123456787654321"
print(a[2])
print(a[0:-4])
print(a[0:4:1])
print(a[::1])

3
12345678765
1234
123456787654321


string length upper lower

In [69]:
a="I am a full stack web developer"
print(a.lower())
print(a.upper())
print(len(a))
print(a.split())
print(a.count('l'))
# reverse a string
print(a[::-1])

i am a full stack web developer
I AM A FULL STACK WEB DEVELOPER
31
['I', 'am', 'a', 'full', 'stack', 'web', 'developer']
3
repoleved bew kcats lluf a ma I


In [65]:
a=9
b=3
a is b

False

In [71]:
##palindrome
s1 = "Indian Army"
s2 = "malayalam"
s3 = "madam"
s4 = "teacher"
print ("s1 -->", s1 == s1[::-1])
print ("s2 -->", s2 == s2[::-1])
print ("s3 -->", s3 == s3[::-1])
print ("s4 -->", s4 == s4[::-1])

s1 --> False
s2 --> True
s3 --> True
s4 --> False


Lists

In [73]:
l= [1,"dia", 042.2]
print(len(l))
print(type(l))

3
<class 'list'>


In [74]:
l= [1,"dia", 042.2]
i=0
while i< len(l):
    print(l[i])
    i=i+1

1
dia
42.2


In [100]:
L = [3, 6, 9, 12, 5, 3, 2]
L1 = ["Rahul", "Thapar", 100, 200]
print(L[::2])
L.append(0)
print(L)
L.insert(3,32)
print(L)
L.extend("dia")
L.extend(["dia"])
L.extend(L1)
print(L)
del L[3]
L.remove(5)
L.pop(4)
del(L1)
print(L)
L = [3, 6, 9, 12, 5, 3, 2]

print(sum(L)/len(L))
print(min(L))
L.sort()
print(L)
sorted(L)
print(L)
print(L+L)

[3, 9, 5, 2]
[3, 6, 9, 12, 5, 3, 2, 0]
[3, 6, 9, 32, 12, 5, 3, 2, 0]
[3, 6, 9, 32, 12, 5, 3, 2, 0, 'd', 'i', 'a', 'dia', 'Rahul', 'Thapar', 100, 200]
[3, 6, 9, 12, 2, 0, 'd', 'i', 'a', 'dia', 'Rahul', 'Thapar', 100, 200]
5.714285714285714
2
[2, 3, 3, 5, 6, 9, 12]
[2, 3, 3, 5, 6, 9, 12]
[2, 3, 3, 5, 6, 9, 12, 2, 3, 3, 5, 6, 9, 12]


In [101]:
import random as r
n=110
L=[]
for i in range(n):
    L.append(r.randint(1,100))
print(L)


[39, 80, 47, 64, 23, 69, 84, 52, 32, 35, 69, 44, 52, 84, 14, 4, 34, 6, 96, 82, 98, 2, 3, 15, 8, 55, 22, 22, 67, 68, 64, 37, 10, 26, 28, 37, 17, 79, 13, 36, 22, 2, 46, 41, 52, 73, 44, 47, 57, 27, 57, 93, 71, 82, 44, 75, 45, 95, 64, 23, 18, 25, 98, 22, 20, 86, 60, 57, 1, 52, 45, 31, 93, 92, 34, 90, 5, 42, 91, 79, 19, 95, 10, 49, 75, 97, 100, 74, 66, 54, 22, 43, 6, 87, 26, 16, 39, 20, 3, 37, 45, 9, 99, 91, 49, 40, 57, 85, 28, 51]


In [102]:
n=12
L=[]
L=[ r.randint(1,100) for i in range(n)]
print(L)

[5, 18, 5, 70, 39, 59, 6, 49, 92, 75, 20, 67]


In [103]:
import string as s
n=12
m=2
L=[]

for i in range(n):
    L.append("".join(r.sample(s.ascii_letters,m)))
print(L)

['SR', 'GC', 'kt', 'dA', 'PD', 'Nx', 'cL', 'mR', 'nh', 'JV', 'Oz', 'yj']


In [110]:
L=["".join(r.sample(s.ascii_letters,12)) for i in range(23)]
n = [ "".join(r.sample(s.ascii_letters, r.randint(5,10))) for i in range(12)]
import copy
print(L)
print(n)
print(12 in L)
L1 = copy.copy(L)                       # Pointing to the same memory location as L
print(L1)

['kRVjmPHOpguf', 'oEnljFUtQImW', 'hxGVveDrSnEs', 'UAilveXVfEkn', 'ODFMqAvNCJSa', 'zDsQgGWejFcq', 'HnpuDMwqAVmN', 'vHEnJkezpxFB', 'jWtFVJuCLexa', 'zeKRYgBIbMZx', 'iklvFGmZPMdI', 'JARmxWXbjZvd', 'qEDKXxAHNYzr', 'sgMCuSnQKWhO', 'NlzpesDGjXcu', 'YEFmJwhtVcGR', 'ohQpNcPtVrzq', 'RtDqfdbIHMCS', 'JoSEIrkUHRcx', 'pHhiPURXbEgJ', 'IkhDHvdGUuNn', 'mGISFPBOtiXs', 'TLXokDPwOnga']
['jkdBLQmWw', 'VeBibYmA', 'oQfzFK', 'DbyQtiHBcO', 'shqjB', 'BnRUdrVvAp', 'pxhcYze', 'eozJg', 'MqCvDaduPy', 'QSnzZWA', 'QvNnOXr', 'hoFEfZKTp']
False
['kRVjmPHOpguf', 'oEnljFUtQImW', 'hxGVveDrSnEs', 'UAilveXVfEkn', 'ODFMqAvNCJSa', 'zDsQgGWejFcq', 'HnpuDMwqAVmN', 'vHEnJkezpxFB', 'jWtFVJuCLexa', 'zeKRYgBIbMZx', 'iklvFGmZPMdI', 'JARmxWXbjZvd', 'qEDKXxAHNYzr', 'sgMCuSnQKWhO', 'NlzpesDGjXcu', 'YEFmJwhtVcGR', 'ohQpNcPtVrzq', 'RtDqfdbIHMCS', 'JoSEIrkUHRcx', 'pHhiPURXbEgJ', 'IkhDHvdGUuNn', 'mGISFPBOtiXs', 'TLXokDPwOnga']


Tuple

In [111]:
T = ("Pratham", 'Sharma', 3.14, 3)
print(len(T))
print(type(T))

4
<class 'tuple'>


In [113]:
T=("Diyaa")
P=("diya",12)
print(len(P))
print(len(T))

2
5


In [114]:
T=("diaaaa")
for s in T:
    print(s)

d
i
a
a
a
a


In [116]:
t=('a','b','c')
print(max(t))
print(min(t))

c
a


In [118]:
T=(1,2,3,45,67,54,2)
print(T[1:2])
print(T[::5])
print(T[-3:-2])
print(T[:-1])
print(T[3:])

(2,)
(1, 54)
(67,)
(1, 2, 3, 45, 67, 54)
(45, 67, 54, 2)


In [122]:
T=(12,34,2,4,21,12)
T1=list(T)
T1.append(342234)
T1.insert(4,"dia")
del T1[3]
T=tuple(T1)
print(T)

(12, 34, 2, 'dia', 21, 12, 342234)


In [123]:
T=(12,34,2,4,21,12)
print(sum(T))
print(sum(T)/len(T))
print(sum(T)//len(T))

85
14.166666666666666
14


In [124]:
n=12
T=tuple([r.randint(1,100) for i in range(n)])
print(T)

(98, 69, 14, 66, 50, 12, 38, 72, 53, 42, 97, 78)


In [129]:
import string as s
n=134
T=tuple(["".join(r.sample(s.ascii_letters,r.randint(5,10))) for i in range(n)])
print(T)

('KvpXgbmD', 'CBKqs', 'EgVOJraMv', 'dyOYzpUram', 'ThziX', 'DvESwTfn', 'yqvSpzW', 'wqznCOd', 'NcerVuAUPW', 'UlXYNCZO', 'EnyzLrSXRB', 'nqdwv', 'zmquO', 'btzfSLYPKZ', 'qXPEFscd', 'jrBhnICR', 'kiPXfoDJQ', 'QomxRbjtIr', 'fvQbXVlO', 'qUXjVFhg', 'FURZKe', 'CNIUoE', 'IHFekt', 'AdSVLI', 'larjCoGS', 'yWXCxmk', 'aZOsbHwUlL', 'UDSzp', 'KahYPT', 'sfUTQkV', 'GZDnqAJB', 'IqsZcfnGXp', 'SmTaWGK', 'vfFMpkJZe', 'tkgsVQfd', 'qYQIPMDLdr', 'fayxiJ', 'qwMLfQ', 'edIiQzBUjJ', 'xpaineyC', 'fyFdBD', 'FGRejV', 'wkrxjI', 'jTLxp', 'KIOEV', 'JXzqS', 'AhMbClL', 'kboBDHEe', 'DTVpW', 'xkVsgoJB', 'frHWbKBQ', 'NpwRblGs', 'QSGzku', 'PugGQ', 'cfkTX', 'kuJahGS', 'eYqZunF', 'kUKzSadIL', 'qePmFrh', 'fyvNwFHsh', 'sbyXHpWaug', 'jANfoFX', 'PEQfObY', 'hIJce', 'LcCIlBo', 'tdLYFDs', 'VUTkBa', 'FBgyRv', 'FkuKEOY', 'OMRcYufxB', 'aGbXSu', 'RyOcpLGwdA', 'MWVhn', 'sNVnjaQE', 'ZySPb', 'TOaSr', 'OprhKR', 'kbdQR', 'mdSMEx', 'PthZUmJdAY', 'ATKCd', 'MypfKtUl', 'xwjqlTVM', 'UIfRG', 'vwpHEjD', 'cTVFzWnZ', 'HKTDX', 'LujRE', 'xQBYNTzA', 'wcZLNFR

In [130]:
T=(1,4,6,3,6,4,36,5,4)
print(4 in T)

True


In [131]:
T1=(3,5,2)
T2=(1,2,3,4,5)
print(T1+T2)

(3, 5, 2, 1, 2, 3, 4, 5)


In [133]:
T=(3,2,4,5,7,8,4,1)
print(T.index(5))
print(T.count(3))

3
1


In [134]:
T=(2,(3,2,1),232)
print(T[1][1])

2


SETS

In [135]:
S={1,23,4}
print(S)
print(len(S))
print(type(S))

{1, 4, 23}
3
<class 'set'>


In [138]:
S=set([1,23])
print(type(S))
for i in S:
    print(i)

<class 'set'>
1
23


In [140]:
S={'A','b','V'}
S.add('E')
print(S)

{'E', 'b', 'A', 'V'}


In [144]:
S={'A','b','V'}
S1={1,23,4}
S.update(S1)
print(S)
S.remove('A')
S.discard('b')
S

{1, 'b', 4, 23, 'A', 'V'}


{1, 23, 4, 'V'}

In [145]:
# if we need to initialise set with null value.. use 
S=set()
# and not
S= {}
# this will initialize a dictionary

In [147]:
#increment every element of set by n
S1={2,1,343,12,3}
n=10

S2=set()
for i in S1:
    S2.add(i+n)

print(S1)
print(S2)

{1, 2, 3, 343, 12}
{353, 11, 12, 13, 22}


In [148]:
n=10
S=set()
for i in range(n):
    S.add(r.randint(1,100))
print(S)

{1, 3, 7, 72, 80, 85, 91, 62}


In [149]:
n=10
S=set()
for i in range(n):
    S.add("".join(r.sample(s.ascii_letters,m)))
print(S)

{'fY', 'If', 'ZG', 'ce', 'bQ', 'AE', 'lr', 'VO', 'XK', 'ND'}


In [150]:
S = set([3, frozenset([10,20,30]), 9, frozenset([12, 5, 3, 2]), "Ram"])
print(S)

{3, 'Ram', 9, frozenset({2, 3, 12, 5}), frozenset({10, 20, 30})}


In [151]:
#------------------------------------------------------------------------
# 1.24: Use of copy() function
#------------------------------------------------------------------------
# Example 1
S1 = {1, 2, 3, 4, 5, 6}

S2 = S1                            # Pointing to the same memory location as S1
S2.add(100)

print ("S1 -->", S1)
print ("S2 -->", S2)


S1 --> {1, 2, 3, 4, 5, 6, 100}
S2 --> {1, 2, 3, 4, 5, 6, 100}


Dictionary

in key value pairs

In [156]:
D={1:23, 2:45}
D[5]=2.4
D[1]=32
del D[2]
print(D)
print(D.keys())
print(D.values())


{1: 32, 5: 2.4}
dict_keys([1, 5])
dict_values([32, 2.4])


numpy

In [157]:
import numpy as np

In [158]:
list=[1,2,3]
np.array(list)

array([1, 2, 3])

In [159]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [167]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
print(ranarr)
ranarr.argmax()

[17 31 16 13  2 39 46  4 19  2]


6

In [172]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [173]:
arr[1:4]

array([1, 2, 3])

In [176]:
arr=np.arange(0,12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [177]:
slice=arr[1:3]
print(arr)
print(slice)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[1 2]


In [178]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [179]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [180]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04])

In [182]:
#np.dot()

pandas

In [183]:
import pandas as pd

In [184]:
# second argument in the series is taken as key

In [187]:
d1={'Name':['ho','dfw','fgdvc','rfc'],'marks':[23,34,52,234]}
d2=pd.DataFrame(d1,index=['1',2,4,5])
print(d2)
d2

    Name  marks
1     ho     23
2    dfw     34
4  fgdvc     52
5    rfc    234


Name  marks
1     ho     23
2    dfw     34
4  fgdvc     52
5    rfc    234

In [190]:
df=pd.DataFrame({'A':[r.randint(1,9) for x in range(5)],
                 'B':[r.randint(1,9)*10 for x in range(5)],
                 'C':[r.randint(1,9)**10 for x in range(5)],
                 'D':["".join(r.sample(s.ascii_letters,3)).upper() for x in range(5)]})
print(df)

   A   B           C    D
0  5  10     9765625  KFV
1  4  20  3486784401  ZMW
2  7  90     9765625  OFT
3  1  50   282475249  CAR
4  6  40     9765625  FWR


In [191]:
df.describe()

A          B             C
count  5.000000   5.000000  5.000000e+00
mean   4.600000  42.000000  7.597113e+08
std    2.302173  31.144823  1.529047e+09
min    1.000000  10.000000  9.765625e+06
25%    4.000000  20.000000  9.765625e+06
50%    5.000000  40.000000  9.765625e+06
75%    6.000000  50.000000  2.824752e+08
max    7.000000  90.000000  3.486784e+09

In [193]:
dates= pd.date_range('20041218',periods=6)
dates

DatetimeIndex(['2004-12-18', '2004-12-19', '2004-12-20', '2004-12-21',
               '2004-12-22', '2004-12-23'],
              dtype='datetime64[ns]', freq='D')

In [197]:
import pandas as pd
import numpy as np

dates = pd.date_range('20230101', periods=6)  # Define the index (dates)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=['A','B','C','D'])

df


A         B         C         D
2023-01-01  0.376193  0.228723  0.560398  1.578667
2023-01-02  0.731011 -0.084733 -2.120060 -1.316152
2023-01-03 -0.974035  1.159124 -1.531929  0.413303
2023-01-04 -0.565666  1.194635  0.506421  0.102794
2023-01-05  0.646565  0.279018  0.553289  0.374965
2023-01-06 -1.032987  1.061746 -2.019268  0.023052

In [199]:
df.sort_index(axis=0,ascending=False)

A         B         C         D
2023-01-06 -1.032987  1.061746 -2.019268  0.023052
2023-01-05  0.646565  0.279018  0.553289  0.374965
2023-01-04 -0.565666  1.194635  0.506421  0.102794
2023-01-03 -0.974035  1.159124 -1.531929  0.413303
2023-01-02  0.731011 -0.084733 -2.120060 -1.316152
2023-01-01  0.376193  0.228723  0.560398  1.578667

In [200]:
df.sort_values(by='C', ascending=False)

A         B         C         D
2023-01-01  0.376193  0.228723  0.560398  1.578667
2023-01-05  0.646565  0.279018  0.553289  0.374965
2023-01-04 -0.565666  1.194635  0.506421  0.102794
2023-01-03 -0.974035  1.159124 -1.531929  0.413303
2023-01-06 -1.032987  1.061746 -2.019268  0.023052
2023-01-02  0.731011 -0.084733 -2.120060 -1.316152