In [9]:
import numpy as np

In [3]:
#ques1
x=np.array([[1,2,3],[4,5,6]])
x[:,[0,1]]=x[:,[1,0]]
x

array([[2, 1, 3],
       [5, 4, 6]])

In [5]:
#ques2
x=np.array([[1,2,3],[4,5,6]])
rev= x[::-1]
rev

array([[4, 5, 6],
       [1, 2, 3]])

In [7]:
#ques 3
a=np.array([1,2,3,4,5,6,7,8])
a[(a >= 2) & (a <= 5)] *= -1
a


array([ 1, -2, -3, -4, -5,  6,  7,  8])

In [24]:
#ques 4
a=np.array([[1,2,3,4,5],[6,7,8,9,0],[1,3,4,5,6],[6,5,4,3,2],[3,5,6,7,4]])
a
mean = a.mean()
res= a- mean
print(a)
print(res)

[[1 2 3 4 5]
 [6 7 8 9 0]
 [1 3 4 5 6]
 [6 5 4 3 2]
 [3 5 6 7 4]]
[[-3.36 -2.36 -1.36 -0.36  0.64]
 [ 1.64  2.64  3.64  4.64 -4.36]
 [-3.36 -1.36 -0.36  0.64  1.64]
 [ 1.64  0.64 -0.36 -1.36 -2.36]
 [-1.36  0.64  1.64  2.64 -0.36]]


In [ ]:
# ques 5
a=np.array([[1,2,3,4,5],[6,7,8,9,0],[1,3,4,5,6],[6,5,4,3,2],[3,5,6,7,4]])
