In [1]:
import numpy as np

In [3]:
arr= np.array([[1,2,3,4],[6,7,8,9]])
arr.shape

(2, 4)

In [4]:
arr

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [8]:
arr[0][1]

2

In [9]:
arr[0][1]=12
arr

array([[ 1, 12,  3,  4],
       [ 6,  7,  8,  9]])

In [12]:
arr[:1]

array([[ 1, 12,  3,  4]])

In [13]:
## ndim= number of dimensions
arr.ndim

2

In [15]:
len(arr.shape)

2

In [16]:
arr.dtype

dtype('int32')

In [23]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
res1 = arr1 + arr2
res2 = arr1 - arr2
res3 = arr1 * arr2
res4 = arr1 / arr2

print(res1)
print(res2)
print(res3)
print(res4)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [24]:
arr3= np.array([[1,2,3,4],[6,7,8,9],[8,9,10,12]])
arr3.ndim

2

In [27]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [39]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)
## axis=0 means the operation is performed about axis=1 row wise

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
x.size

4

In [32]:
n = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]],
                [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])

In [33]:
n.ndim

4

In [38]:
## isse array ke dimensions change hote h
b = y.reshape(2,1)
b

array([[5],
       [6]])

In [40]:
np.zeros(2,dtype=int)

array([0, 0])

In [41]:
a = np.array([1, 2, 3, 4, 5, 6])
a2 = a[np.newaxis, :]
a2

array([[1, 2, 3, 4, 5, 6]])

In [45]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [46]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [47]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
np.vstack((a1, a2))
## vertical stack

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [48]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [51]:
x=np.arange(1,25).reshape(2,12)
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]