In [16]:
! pip install numpy

In [17]:
print("helo")

helo


In [18]:
import numpy as np

In [19]:
my_lst= [1,2,3,4,5]
arr= np.array(my_lst)

In [20]:
type(arr)

numpy.ndarray

In [21]:
print(arr)

[1 2 3 4 5]


In [22]:
arr

array([1, 2, 3, 4, 5])

In [23]:
arr.shape

(5,)

In [26]:
my_lst1= [1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[3,4,7,4,8]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [27]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 7, 4, 8]])

In [28]:
arr.shape

(3, 5)

In [ ]:
arr.reshape(5,3)